### ISSUE TITLE
Does not compile with gcc 11.1.0

### ISSUE THREAD

**Issue by saemy** [biocore-ntnu/ncls#45]
The following error occurs:
```
ncls/src/fncls.c: In function ‘__pyx_tp_dealloc_4ncls_3src_5fncls_FNCLS’:
ncls/src/fncls.c:17105:5: error: lvalue required as increment operand
17105 |     ++Py_REFCNT(o);
      |     ^~
ncls/src/fncls.c:17107:5: error: lvalue required as decrement operand
17107 |     --Py_REFCNT(o);
      |     ^~
```
